v: 3
grpcAddress: "unix://Users/my/path/consul-gslb-driver/socket" # --grpcAddress
consulConfig:
  scheme: "http"
  datacenter: "teh1"
  address: "consul-ui.consul.svc.cluster.local"
metricServer:
  ip: "127.0.0.1"
  port: 9876 # --metrics-port
  path: "/metrics"
