// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gslbi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerClient interface {
	CreateGSLB(ctx context.Context, in *CreateGSLBRequest, opts ...grpc.CallOption) (*CreateGSLBResponse, error)
	DeleteGSLB(ctx context.Context, in *DeleteGSLBRequest, opts ...grpc.CallOption) (*DeleteGSLBResponse, error)
	ControllerGetGSLB(ctx context.Context, in *ControllerGetGSLBRequest, opts ...grpc.CallOption) (*ControllerGetGSLBResponse, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) CreateGSLB(ctx context.Context, in *CreateGSLBRequest, opts ...grpc.CallOption) (*CreateGSLBResponse, error) {
	out := new(CreateGSLBResponse)
	err := c.cc.Invoke(ctx, "/gslbi.v1.Controller/CreateGSLB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DeleteGSLB(ctx context.Context, in *DeleteGSLBRequest, opts ...grpc.CallOption) (*DeleteGSLBResponse, error) {
	out := new(DeleteGSLBResponse)
	err := c.cc.Invoke(ctx, "/gslbi.v1.Controller/DeleteGSLB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ControllerGetGSLB(ctx context.Context, in *ControllerGetGSLBRequest, opts ...grpc.CallOption) (*ControllerGetGSLBResponse, error) {
	out := new(ControllerGetGSLBResponse)
	err := c.cc.Invoke(ctx, "/gslbi.v1.Controller/ControllerGetGSLB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility
type ControllerServer interface {
	CreateGSLB(context.Context, *CreateGSLBRequest) (*CreateGSLBResponse, error)
	DeleteGSLB(context.Context, *DeleteGSLBRequest) (*DeleteGSLBResponse, error)
	ControllerGetGSLB(context.Context, *ControllerGetGSLBRequest) (*ControllerGetGSLBResponse, error)
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (UnimplementedControllerServer) CreateGSLB(context.Context, *CreateGSLBRequest) (*CreateGSLBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGSLB not implemented")
}
func (UnimplementedControllerServer) DeleteGSLB(context.Context, *DeleteGSLBRequest) (*DeleteGSLBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGSLB not implemented")
}
func (UnimplementedControllerServer) ControllerGetGSLB(context.Context, *ControllerGetGSLBRequest) (*ControllerGetGSLBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControllerGetGSLB not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_CreateGSLB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGSLBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).CreateGSLB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gslbi.v1.Controller/CreateGSLB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).CreateGSLB(ctx, req.(*CreateGSLBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DeleteGSLB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGSLBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DeleteGSLB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gslbi.v1.Controller/DeleteGSLB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DeleteGSLB(ctx, req.(*DeleteGSLBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ControllerGetGSLB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControllerGetGSLBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).ControllerGetGSLB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gslbi.v1.Controller/ControllerGetGSLB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).ControllerGetGSLB(ctx, req.(*ControllerGetGSLBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gslbi.v1.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGSLB",
			Handler:    _Controller_CreateGSLB_Handler,
		},
		{
			MethodName: "DeleteGSLB",
			Handler:    _Controller_DeleteGSLB_Handler,
		},
		{
			MethodName: "ControllerGetGSLB",
			Handler:    _Controller_ControllerGetGSLB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gslbi/gslbi.proto",
}
